---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  annotations:
    dotmeshName: moby_counter@master
spec:
  storageClassName: dotmesh
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
